### PR TITLE
Added padding options

### PR DESCRIPTION
**Pull request by sichenn**
Upon imported into game engines, some tightly fit sprites would bleed/leak. 
The padding option is added into export settings to remove the need to directly tweak the canvas itself.

### CODE REVIEW

**Comment by bogdanrybak** [comment]
Hey! Thank you for this pull request. Amazing additional feature that solves a common issue. My only worry is that we're changing the csv format to include padding. That will break some in-game-engine importing logic for people, including myself.

Do you think we could make inclusion of padding information an optional checkbox? So by default the text file would include padding in the width / height?

**Comment by sichenn** [comment]
Yes, I forgot to consider that! I'll shortly fix this issue🤪

**Comment by sichenn** [comment]
A checkbox has been added! By default it's unchecked and padding would be included in the width / height. All the files and instructions have been updated too. If there's any other problems please let me know. I'll be happy to fix them!

**Comment by bogdanrybak** [comment]
All works well @SebaschenLiu . Great enhancement overall!

Thank you for contributing 😃👍

**Pull request merged**
